(function(){
'use strict';
const REPO='mathias82/log-doctor';
function clean(value){return String(value??'').replace(/```/g,'').trim()}
function unknownIncidents(payload){return (payload&&payload.incidents||[]).filter(i=>String(i.type||'').toUpperCase()==='UNKNOWN'||i.humanReviewRequired===true)}
function issueFor(payload){
 const incidents=unknownIncidents(payload);if(!incidents.length)return null;
 const first=incidents[0],redaction=payload.redactionReport||{};
 const evidence=clean(first.evidence||'No redacted evidence available.').slice(0,4000);
 const category=clean(first.category||'UNKNOWN');
 const title=`Unknown ${category} failure: deterministic rule candidate`.slice(0,180);
 const body=[
  '## Unknown failure contribution','',
  '> Generated by Log Doctor. Please review before submitting. Do not add credentials, tokens, customer data, or other sensitive information.','',
  '### Context',`- Category: \`${category}\``,`- Current diagnosis type: \`${clean(first.type||'UNKNOWN')}\``,`- Human review required: \`${Boolean(first.humanReviewRequired)}\``,`- Redactions detected in original analysis: \`${Number(redaction.totalRedactions||0)}\``,'',
  '### Sanitized evidence','```text',evidence,'```','',
  '### What should Log Doctor diagnose?','<!-- Describe the expected deterministic diagnosis/root cause. -->','',
  '### Expected investigation guidance','<!-- What should an engineer inspect or validate? -->','',
  '### Environment','<!-- Optional: Java/Spring/Kafka/DB versions if relevant. Do not include private infrastructure details. -->','',
  '### Safety check','- [ ] I reviewed the generated content and removed any sensitive or organization-specific data.','- [ ] The example is safe to publish in a public GitHub issue.','',
  '_This issue is a proposal for a deterministic diagnostic rule. It does not authorize automatic remediation._'
 ].join('\n');
 return {title,body};
}
function issueUrl(payload){const issue=issueFor(payload);if(!issue)return null;return `https://github.com/${REPO}/issues/new?title=${encodeURIComponent(issue.title)}&body=${encodeURIComponent(issue.body)}`}
window.LogDoctorContribution={unknownIncidents,issueFor,issueUrl};
})();
