package io.github.mathias82.logdoctor.engine;

import io.github.mathias82.logdoctor.core.Incident;
import io.github.mathias82.logdoctor.core.IncidentCategory;
import io.github.mathias82.logdoctor.llm.LlmClient;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

class DiagnosisEngineTest {
    private final DiagnosisEngine engine=new DiagnosisEngine(new StubLlmClient());
    @Test void returnsNoFailureForBlankInput(){var r=engine.analyzeStructured("   ");assertThat(r.status()).isEqualTo("NO_FAILURE");assertThat(r.llmUsed()).isFalse();assertThat(r.humanReviewRequired()).isFalse();assertThat(r.matchScore()).isZero();assertThat(r.matchConfidence()).isEqualTo("NONE");assertThat(r.remediation()).isNull();}
    @Test void returnsNoFailureWhenNoExceptionIsPresent(){var r=engine.analyzeStructured("2026-09-01 INFO application started successfully");assertThat(r.status()).isEqualTo("NO_FAILURE");assertThat(r.summary()).contains("No obvious failure");}
    @Test void usesLlmForUnknownFailure(){var r=engine.analyzeStructured("java.lang.RuntimeException: boom");assertThat(r.status()).isEqualTo("UNKNOWN");assertThat(r.type()).isEqualTo("UNKNOWN_FAILURE");assertThat(r.llmUsed()).isTrue();assertThat(r.fixType()).isEqualTo("NO_AUTOMATIC_FIX");assertThat(r.diagnosis()).contains("stub unknown analysis");assertThat(r.matchScore()).isZero();assertThat(r.matchConfidence()).isEqualTo("NONE");assertThat(r.remediation().safety()).isEqualTo("HUMAN_REVIEW_REQUIRED");assertThat(r.remediation().automaticExecutionAllowed()).isFalse();}
    @Test void fallsBackToHumanReviewWhenLlmIsUnavailable(){var r=new DiagnosisEngine(new FailingLlmClient()).analyzeStructured("java.lang.RuntimeException: boom");assertThat(r.llmUsed()).isFalse();assertThat(r.humanReviewRequired()).isTrue();assertThat(r.fix()).contains("LLM analysis is unavailable");assertThat(r.diagnosis()).doesNotContain("LLM ANALYSIS:");}
    @Test void treatsBlankLlmResponseAsUnavailable(){var r=new DiagnosisEngine(new BlankLlmClient()).analyzeStructured("java.lang.RuntimeException: boom");assertThat(r.llmUsed()).isFalse();assertThat(r.humanReviewRequired()).isTrue();}
    @Test void marksConcurrencyFailureForHumanReviewWithoutCallingLlm(){var r=engine.analyzeStructured("org.hibernate.OptimisticLockException: row was updated by another transaction");assertThat(r.type()).isEqualTo("CONCURRENCY_FAILURE");assertThat(r.category()).isEqualTo("THREADING");assertThat(r.humanReviewRequired()).isTrue();assertThat(r.remediation().verificationSteps()).anyMatch(s->s.contains("concurrent load"));assertThat(r.remediation().automaticExecutionAllowed()).isFalse();}
    @Test void infersInfrastructureCategoryCaseInsensitively(){var r=engine.analyzeStructured("java.net.SocketTimeoutException: timeout from RestTemplate");assertThat(r.category()).isEqualTo("INFRASTRUCTURE");assertThat(r.remediation().safety()).isEqualTo("HUMAN_REVIEW_REQUIRED");}
    @Test void exposesCauseChainForNestedExceptions(){String log=String.join(System.lineSeparator(),"org.springframework.beans.factory.BeanCreationException: failed to create bean","at com.acme.App.start(App.java:10)","Caused by: java.lang.IllegalStateException: client failed","at com.acme.Client.call(Client.java:20)","Caused by: java.net.ConnectException: Connection refused");var r=engine.analyzeStructured(log);assertThat(r.causeChain()).hasSize(3);assertThat(r.causeChain().get(2).exceptionType()).isEqualTo("java.net.ConnectException");}
    @Test void explainsWhyDeterministicRuleMatched(){var r=engine.analyzeStructured("java.lang.NoClassDefFoundError: com/acme/Missing");assertThat(r.matchReasons()).isNotEmpty();assertThat(r.matchReasons().get(0)).contains("CommonFailureCatalogRule");}
    @Test void exposesAuditableMatchScoreForCatalogRule(){var r=engine.analyzeStructured("java.lang.NoClassDefFoundError: com/acme/Missing");assertThat(r.matchScore()).isBetween(75,100);assertThat(r.matchConfidence()).isIn("HIGH","VERY_HIGH");assertThat(r.matchScoreFactors()).isNotEmpty();}
    @Test void exposesStructuredRemediationForDeterministicDiagnosis(){var r=engine.analyzeStructured("java.lang.NoClassDefFoundError: com/acme/Missing");assertThat(r.remediation()).isNotNull();assertThat(r.remediation().allowedActions()).contains("JAVA_CODE");assertThat(r.remediation().verificationSteps()).isNotEmpty();assertThat(r.remediation().automaticExecutionAllowed()).isFalse();}
    private static final class StubLlmClient implements LlmClient{public String explainKnownIncident(Incident i){return "stub known analysis";}public String analyzeUnknownLog(String r,IncidentCategory c){return "stub unknown analysis";}}
    private static final class FailingLlmClient implements LlmClient{public String explainKnownIncident(Incident i){throw new IllegalStateException("Ollama unavailable");}public String analyzeUnknownLog(String r,IncidentCategory c){throw new IllegalStateException("Ollama unavailable");}}
    private static final class BlankLlmClient implements LlmClient{public String explainKnownIncident(Incident i){return "  ";}public String analyzeUnknownLog(String r,IncidentCategory c){return "  ";}}
}
